server:
  port: 3344
spring:
  application:
    name: microservicecloud-config-3344
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:kathrinacathy/microserviceclous-config.git  #github上面的地址
          uri: https://github.com/kathrinacathy/microserviceclous-config.git